### ISSUE TITLE
Question: Plotting an Automaton

### ISSUE THREAD

**Issue by glarange** [tulip-control/omega#13]
How do I plot the graph for the expression u below? Thanks, Gui

```from omega.symbolic import temporal as trl
aut = trl.Automaton()
aut.declare_variables(x=(0, 3))
u=aut.add_expr('x = 3')```

**Comment by johnyf** [comment]
What is meant by "the graph for the expression u"?

**Comment by glarange** [comment]
You already answered this over in 
https://github.com/tulip-control/dd/issues/71:
```aut.bdd.dump('example_1.pdf', [u])```
 
Sorry for repeat question. What I got after trying above was:
```FileNotFoundError: [WinError 2] "dot" not found in path```
I suspect this is something to do with graphviz, but am not sure.

**Comment by johnyf** [comment]
So the graph here refers to the BDD that represents `u`.

Yes, the message about `dot` is related to GraphViz.
